// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/ex/ex.proto

package go_micro_srv_ex

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Ex service

type ExService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Ex_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Ex_PingPongService, error)
}

type exService struct {
	c    client.Client
	name string
}

func NewExService(name string, c client.Client) ExService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.ex"
	}
	return &exService{
		c:    c,
		name: name,
	}
}

func (c *exService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Ex.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Ex_StreamService, error) {
	req := c.c.NewRequest(c.name, "Ex.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &exServiceStream{stream}, nil
}

type Ex_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type exServiceStream struct {
	stream client.Stream
}

func (x *exServiceStream) Close() error {
	return x.stream.Close()
}

func (x *exServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *exServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *exServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exService) PingPong(ctx context.Context, opts ...client.CallOption) (Ex_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Ex.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &exServicePingPong{stream}, nil
}

type Ex_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type exServicePingPong struct {
	stream client.Stream
}

func (x *exServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *exServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *exServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *exServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *exServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Ex service

type ExHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Ex_StreamStream) error
	PingPong(context.Context, Ex_PingPongStream) error
}

func RegisterExHandler(s server.Server, hdlr ExHandler, opts ...server.HandlerOption) error {
	type ex interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Ex struct {
		ex
	}
	h := &exHandler{hdlr}
	return s.Handle(s.NewHandler(&Ex{h}, opts...))
}

type exHandler struct {
	ExHandler
}

func (h *exHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ExHandler.Call(ctx, in, out)
}

func (h *exHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ExHandler.Stream(ctx, m, &exStreamStream{stream})
}

type Ex_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type exStreamStream struct {
	stream server.Stream
}

func (x *exStreamStream) Close() error {
	return x.stream.Close()
}

func (x *exStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *exStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *exStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *exHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ExHandler.PingPong(ctx, &exPingPongStream{stream})
}

type Ex_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type exPingPongStream struct {
	stream server.Stream
}

func (x *exPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *exPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *exPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *exPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *exPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
